Ensure we have a post object in vip_legacy_redirect_parent_id
Automattic/legacy-redirector pull request #46
Opened 2019-03-27 18:09 UTC by kjbenk

Fixes issue where a post ID is passed to the `vip_legacy_redirect_parent_id` function when it is expecting an object.

2019-03-29 22:10 UTC, rebeccahum requested changes

2019-03-29 22:10 UTC, rebeccahum commented on wpcom-legacy-redirector.php
> +			$post = get_post( $post );
Before calling `get_post()` unnecessarily, we should check that it's not an object.

2019-03-30 01:45 UTC, kjbenk commented
@rebeccahum I looked into this issue some more and noticed that the real cause was from a `$_POST` var not being set during the CLI command.

https://github.com/Automattic/WPCOM-Legacy-Redirector/blob/master/wpcom-legacy-redirector.php#L453

I update the PR to ensure that during CLI command runs for the `import-from-meta` the proper vars are set.

2019-04-04 09:15 UTC, GaryJones commented
> $_POST var not being set during the CLI command.

Is that even a thing? I can't see any other references to `$_POST` in that file, so I'm not sure why that's there.

The method got [moved](https://github.com/Automattic/WPCOM-Legacy-Redirector/commit/704b52da223554f1ff29b09f1eeda63c415f8145) from the new UI class, but in doing so, this `$_POST` suddenly appeared with no explanation!

2019-04-04 19:31 UTC, emrikol commented
I think this will work for now.  It would be better if we didn't have to fiddle with the global vars, but that sounds like a bigger refactor.

2019-04-04 19:31 UTC, merged